spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/thyme?autoReconnect=true&useSSL=false
    username: thyme
    password: password01
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
server:
  port: 8080
logging:
  level:
    root: info